### PR TITLE
Allow themes and plugins to alter the widget wrapper classes

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Provide mechanism to set classes on the widget wrapper.

### CODE REVIEW

**Comment by gregpriday** [comment]
Hi Adrian

Thanks! Another very useful looking contribution. I'll review and merge this over the weekend.

**Comment by dimitrov-adrian** [comment]
Any chance to get this in development branch soon?

**Comment by gregpriday** [comment]
Sorry about the wait, I've done some basic reviews, I just need to double check if there are any implications of changing the first argument of siteorigin_panels_the_widget from a class string to the full array. I don't think there will be any, but I do need to just check this first.

**Comment by dimitrov-adrian** [comment]
With 2.1 have no problems. Also siteorigin_panels_the_widget()  is only used in siteorigin_panels_render().
Neither and in panels-lite branch :)

**Comment by gregpriday** [comment]
Merged :)

Yeah, you're right about the siteorigin_panels_the_widget function only being called from siteorigin_panels_render, my only slight concern was for plugin developers who might have used siteorigin_panels_the_widget, but this is highly unlikely.

**Pull request merged**
