### PR TITLE
Layout Export: Fix post title detection in Block Editor

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/siteorigin-panels/issues/798

The title wasn't previously showing as the Block Editor title field is set up slightly differently.

### CODE REVIEW

**Comment by Misplon** [comment]
I can't seem to get this branch to work as it should. My JSON exports are still labeled with the ID only. For example `23992.json`.

**Comment by Misplon** [comment]
@AlexGStapleton Can you confirm that the JSON export file is being labelled correctly for you? Thanks.

**Comment by AlexGStapleton** [comment]
I can confirm the export is working as expected for me. Did you run `build:dev`? Sorry, I should have mentioned this previously.

**Comment by Misplon** [comment]
Thanks for confirming. I usually run the build script while testing. I'm not sure what the issue is, I'll re-test shortly and get back to you.

**Comment by Misplon** [comment]
Thanks, this branch is now working. Should we not add a suffix with the SO Layout Block or something like that. Right now if you have two SO Layout Blocks and try download both your file names will be:

block-editor.json
block-editor (1).json

The (1) being issues by macOS in this case.

**Comment by AlexGStapleton** [comment]
How does that look?

**Comment by Misplon** [comment]
Is the page title being repeated for you? It seems to be for me:

block-editor-block-editor-0.json
block-editor-block-editor-1.json

**Comment by AlexGStapleton** [comment]
Oh. I misread your last reply and had thought you wanted the file to be called "page-name-block-layout-1.json". I'll correct this shortly.

**Comment by Misplon** [comment]
Looking good.

**Pull request merged**
