### PR TITLE
Use the css class value from the widget instance

### PR DESCRIPTION
**Pull request by LoloIrie**
Hi,

a minor modification to use the css class value of the widget instance in the widgets panel...

Cheers
Laurent

### CODE REVIEW

**Comment by LoloIrie** [comment]
Any chance to get this minor modif ?

**Comment by LoloIrie** [comment]
Up ^^

**Comment by LoloIrie** [comment]
It allows something like...

https://siteorigin.com/thread/process-raw-widgets-that-have-come-from-the-page-builder-front-end/#comment-98326

Thanks ;)

**Comment by LoloIrie** [comment]
Any issue with this pull request ?

**Comment by LoloIrie** [comment]
Up

**Comment by braamgenis** [comment]
Closing old PR as stale. Feel free to open a new issue for discussion.

**Comment by LoloIrie** [comment]
Any reason why this PR was not used ?

**Comment by braamgenis** [comment]
Hi @LoloIrie We're in the process of trying to clean up our repos and catch up with PRs that we never got around to reviewing, such as this one. Due to the age of this PR and the fact that there was a merge conflict that needed to be resolved, it's simpler to close the PR and, as I stated above, you can open a new issue to describe the problem and we can discuss the possible solution there and then you're welcome to submit a new PR.

**Pull request closed without merging**
