### PR TITLE
Add filters inside row.

### PR DESCRIPTION
**Pull request by jtmcgrath**
Hey,

This is an updated version of PR #309 for the 3.0 update of Page Builder.

Example use case is to have the row's background across the full width of the screen, but the row's content wrapped in a div with a max-width.

Love the plugin, thanks for making it!

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
This is unrelated to the commit at hand (I think it's a good idea) but I just want to chime in and say that, this:

> Example use case is to have the row's background across the full width of the screen, but the row's content wrapped in a div with a max-width.

Is already possible through the full width row layout. This change will make it possible to automate this without having to filter the default row layout or using JS/CSS though.

**Comment by jtmcgrath** [comment]
Good point @Alex, it's been a while since I've tried using the different layouts.

From what I remember it wasn't easy to override the CSS which controls the layout - we use a class to control the content column width and keep it consistent throughout a site, whereas using the in-built layouts ended up requiring a fair bit of overriding CSS, especially if we wanted to use flex for the layout.

Will check out the new version to see if that's no longer a problem!

**Comment by AlexGStapleton** [comment]
2.5 actually uses flex for most of the structure so things may be easier now.

**Comment by jtmcgrath** [comment]
Oh nice, sounds like there's a lot for me to catch up on!

**Pull request closed without merging**
