### PR TITLE
add hook to inject HTML before and after cell loop; fix #147

### LINKED ISSUE #147: Add hook to inject HTML before and after cell loop
I am proposing here to add hook to add HTML before and after cell loop while rendering panels in `siteorigin_panels_render` function.

There are hooks to add HTML content before and after row. But I want to wrap all cells with a div to apply extra styling. Adding those hooks will be great. I am submitting patch later.

Thanks

### PR DESCRIPTION
**Pull request by ernilambar**
There are hooks to add HTML content before and after row. But I want to wrap all cells with a div to apply extra styling. Adding those hooks will be great. I am submitting patch later.

### CODE REVIEW

**Comment by gregpriday** [comment]
Thanks for the contribution @ernilambar! I'll take a proper look at this when I have some fresher eyes. I know it's a fairly straight forward PR, but for things like adding hooks and filters, we want to make sure that they're added in a very consistent way. Things like naming conventions, arguments and even the order of the arguments are all important.

**Comment by ernilambar** [comment]
Make sense. We should definitely follow a standard for adding action and filter. Will keep on eye on this ticket and hope we will be able to make decision about it. Now I am using very hacky way by using custom javascript for wrapping cell elements.

**Comment by brettsmason** [comment]
I would love to see this added - this would solve a current headache I have very easily :+1:
Great plugin by the way! :smile:

**Comment by gregpriday** [comment]
We actually added this with the new renderer. It was part of a broader rewrite of the renderer. It'll be available in the Page Builder 2.5 update.

**Pull request closed without merging**
