### PR TITLE
Cell Edit Icons

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/siteorigin-panels/issues/874

This PR adds cell edit icons that appear when the cells are too small to allow for the text without expanding to a different line.
Please note that this PR will require a build to test.

Before:

After:

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, mate. Can you check the Live Editor? That'll probably be where these are seen the most.

**Comment by AlexGStapleton** [comment]
It does get a bit hard to use when there's a large number of cells so I've added an additional collapse point for both the Live Editor and standard builder. Please note that rows will be larger in the live editor when the smaller collapse point is being used - this is to ensure all icons are visible.





Oh, and I had forgotten to mention but this PR will require a build - I've amended the original PR comment to mention this.

**Comment by AlexGStapleton** [comment]
It's possible for all of the options (text, icons, icons small) to be used in a row:

https://user-images.githubusercontent.com/17275120/122682539-612b5580-d23d-11eb-8890-3408696fa147.mp4

**Comment by Misplon** [comment]
Super, thanks. Awesome improvements, definitely making progress. I uploaded a build to the demo server. Can you perhaps take a look and let me know if we can do anything about the below?

Screenshot 2021-06-21 at 12 05 52

Screenshot 2021-06-21 at 12 06 22

**Comment by AlexGStapleton** [comment]
I've had a look at the demo site and it appears to be using the version prior to the last commit.

Here's the (privately published) page I was testing:
https://demo.siteorigin.com/north/wp-admin/post.php?post=575&action=edit

Here's what the archives widget of the right of the first looks like for me on hover:


Here's the same row/widget on the demo site:


I went to upload a build to the demo site but for whatever reason I can't actually delete plugins. Can you please try [this build](https://drive.google.com/uc?id=18LPiz5feEi5yzPjR4qbGBXTj6exmqix-)? I've tested this build locally and can confirm it works as expected for me.

**Comment by Misplon** [comment]
Thanks, mate. Can we try address the below?

Screenshot_2021-06-21_at_15_11_32

**Comment by AlexGStapleton** [comment]
Are you using the provided build? Here's what I see when I hover that widget:

**Comment by Misplon** [comment]
Yeah, you can see the build is installed if you head over to plugins. Let me try incognito.

**Comment by AlexGStapleton** [comment]
The last commit will apply the styling of the small icons to all icons when in the live editor. This should ensure it's always easier to access the icons.



I'm going to increase the collapse point of the small icons as they don't appear to be appearing as often as they should.

**Comment by AlexGStapleton** [comment]
Icons will now appear when the cell is 215px wide (was182px). The smaller icons will appear when the cell is 125px wide (was 95px). 
@Misplon Feel free to fine tune these amounts, just note that you'll need to either make a build or be running `build:dev` to see a difference.

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]

**Pull request merged**
