### PR TITLE
jQuery Migrate / WP 5.6 changes

### PR DESCRIPTION
**Pull request by AlexGStapleton**
WB PR: https://github.com/siteorigin/so-widgets-bundle/pull/1208

A large number of changes were made - too many to really list in a readable way. Test _everything_.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
I've come across a few notices that are triggered by us, but they can't be fixed by us:

- When opening/duplicating a row/widget, WP Color Picker will trigger a notice.
- When selecting a colour using the colour picker, Iris will trigger a notice.

**Comment by Misplon** [comment]
Hopefully, those will be resolved before the release https://core.trac.wordpress.org/ticket/51621.

**Comment by AlexGStapleton** [comment]
Oh sorry, thought I flagged this as a ready for review. This PR is a major update so please try doing _everything_.
I'm working on the WB and Premium updates so it's possible you may run into issues viewing page builder generated pages.

**Comment by AlexGStapleton** [comment]
WB PR ready: https://github.com/siteorigin/so-widgets-bundle/pull/1208

**Review by Misplon — APPROVED** [review]

**Review by gregpriday — APPROVED** [review]
Everything looks good to me.

**Pull request merged**
