### PR TITLE
Admin: Show Widget Action links on mobile devices

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/siteorigin-panels/issues/718.

The description is hidden to achieve this.

### CODE REVIEW

**Comment by Misplon** [comment]
Do we perhaps want to rather use `is_mobile` for this?

**Comment by AlexGStapleton** [comment]
We don't currently have a dedicated mobile-specific stylesheet for the admin interface. We can add one, but it seems a tad odd to do this for just this change so if we do this we should move all mobile CSS there. Do you want me to proceed?

I should mention that the breakpoint I'm using is the same value consistently used throughout the stylesheet.

**Comment by Misplon** [comment]
That makes sense. Do we perhaps want to expand this change so that it applies to say an iPhone 10 in landscape?

**Comment by Misplon** [comment]
The widget title is resizing in Chrome when you switch to landscape. I thought I had previously resolved this. Do you want to fix that in this PR if you can replicate?

IMG_0681

**Comment by Misplon** [comment]
`-webkit-text-size-adjust: 100%;` is the solution.

**Comment by AlexGStapleton** [comment]
I can't replicate that in Chrome. It may be a MacOS specific issue. Can you commit the suggested fix? I mean, I can but I can't check if it works before committing.

**Comment by Misplon** [comment]
Thanks, sorted.

Do you want to take a look at the Add Widget search form and try to improve it for mobile?

**Comment by Misplon** [comment]
We can do that in another PR though.

**Pull request merged**
