### PR TITLE
Post Loop: Resolve notice when used outside of Page Builer

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/siteorigin-panels/issues/791

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, mate. This PR resolves #791 but it appears to break https://github.com/siteorigin/siteorigin-panels/pull/781, at least from what I can see in my local testing. I tested using a custom loop using the pagination suggested in the PR. I inserted two Post Loop widgets in the Classic Editor on the same page and selected a different taxonomy in each loop. Clicking to page 2 seems to impact both loops.

**Comment by AlexGStapleton** [comment]
The last commit allows the previously provided PHP to work.

**Comment by Misplon** [comment]
Thanks. This only works if one of the two loops in use doesn't have more pages than each other. Using the new theme unit test data, the classic category produces four pages and the block category produces 2 pages. Each loop hangs onto its page as long as I don't go over the lowest max. So if I select page 2 for the classic loop, the block loop stays on page 1. But I select page 4 for the classic loop, the block loop goes to not found.

Home_-_SiteOrigin

**Comment by AlexGStapleton** [comment]
That appears to be an issue with Corp. I can't replicate this while using a different theme and rolling back to PB `2.10.17` (before the initial PR) still results in the 404 for the second query. Are you able to replicate this while using a different theme?

**Comment by Misplon** [comment]
In North, I'm getting the following:

```Notice: Undefined index: _sow_form_id in /Users/misplon/Sites/siteorigin/wp-content/plugins/siteorigin-panels/inc/widgets/post-loop.php on line 153

Notice: Undefined index: _sow_form_id in /Users/misplon/Sites/siteorigin/wp-content/plugins/siteorigin-panels/inc/widgets/post-loop.php on line 153```

**Comment by Misplon** [comment]
Ok, those notices appear after changing themes. It appears as though the Post Loop widget has changed to a template the new theme has but the widget is holding onto the previous template value.

**Comment by Misplon** [comment]
Page_Builder_-_SiteOrigin

The same issue persists in North.

To confirm, loop one on the page has four pages. Loop two on the page has two pages. If I select page 2 in loop one, loop two will remain on page 1. But if I select a page in loop one that loop two doesn't have, loop two goes 404. Can you confirm this is the test you've run?

**Comment by AlexGStapleton** [comment]
I can confirm that's the test I ran, and I can't replicate this issue while not using Corp.

I can replicate this issue while not using the snippet provided in #781 and while using an older version of PB. Are you able to replicate this issue if you're not using the snippet provided in #781? If so, are you able to replicate this while using PB `2.10.17`?

**Comment by AlexGStapleton** [comment]
> In North, I'm getting the following:

It turns out that id isn't reliable either. The last commit will generate a random number when the post loop widget is saved and that will be used for the pagination. `rand()` isn't truly unique, but it's good enough for our usage.

**Comment by Misplon** [comment]
Does the custom pagination need to be adjusted? Is the following still good?

```	<?php echo paginate_links( array(
		'format'       => '?page-' . SiteOrigin_Panels_Widgets_PostLoop::get_current_pagination_id() . '=%#%',
		'prev_next'    => false,
	) );```

**Comment by AlexGStapleton** [comment]
Yes, that code is still fine. Please note that you must save the Post Loop widget for the ID used by the pagination to be generated. If you don't resave the widget, the provided code won't work as expected. (it'll come up as `?page-=2`).

Regarding the 404 issue you're facing, that's not going to be resolved by the last commit. My last question still remains:
> Are you able to replicate this issue if you're not using the snippet provided in #781? If so, are you able to replicate this while using PB 2.10.17?

**Comment by Misplon** [comment]
The 404 issue persisted before this PR, yes.

**Comment by Misplon** [comment]
At the moment, if I change the page in the normal loop it's impacting the custom pagination loop but not the other way around. Here is a screencast showing my testing setup.

[post-loop-custom.mov.zip](https://github.com/siteorigin/siteorigin-panels/files/5011986/post-loop-custom.mov.zip)

**Comment by Misplon** [comment]
Unless I've misunderstood the testing required here, are both loops meant to be using custom pagination?

**Comment by Misplon** [comment]
Ok, both using custom loops works, my bad.

**Comment by AlexGStapleton** [comment]
Thank you for the video. That's a tricky situation. I'm unsure how we can really get around that as that's happening as we're still looking for the base pagination. Hm. We could add a filter to selectively disable the standard pagination (basically, bypass the other checks) on a widget by widget basis. Yeah, that feels like the way to go. How does `siteorigin_panels_post_loop_custom_pagination` or `siteorigin_panels_post_loop_use_custom_pagination` sound? It would be a boolean check.

**Comment by Misplon** [comment]
`siteorigin_panels_post_loop_custom_pagination` sounds good. Thanks.

**Comment by AlexGStapleton** [comment]
The last commit adds `siteorigin_panels_post_loop_custom_pagination`. To enable it please add `add_filter( 'siteorigin_panels_post_loop_custom_pagination', '__return_true' );` to your test site.

**Comment by Misplon** [comment]
Looks good. We ready to move this onto review?

**Pull request merged**
