### PR TITLE
Added setting for cell spacing in a collapsed row

### PR DESCRIPTION
**Pull request by gregpriday**
Basics of the setting are in place and working. We just need to decide on language to use. Should this be called mobile cell spacing/margin/gutter?

### CODE REVIEW

**Comment by gregpriday** [comment]
@AlexGStapleton can you check that this is all working properly. Also, if you have any feedback on what sort of wording we should use, that'd be a huge help.

**Comment by Misplon** [comment]
The wording looks good to me.

**Comment by AlexGStapleton** [comment]
I'm also fine with the wording.

**Comment by Misplon** [comment]
@AlexGStapleton Please, also check out the functionality when able. Thanks.

**Comment by AlexGStapleton** [comment]
I'm sorry, I should have mentioned that I checked the functionality prior to approving the PR. I didn't run into any issues and everything worked as expected.

**Comment by Misplon** [comment]
Awesome, thanks for confirming.

**Pull request merged**
