### PR TITLE
Dropdown button for prebuilt dialog options.

### PR DESCRIPTION
**Pull request by braamgenis**
Basic dialog button handling for elements in toolbar with .so-toolbar-button class.

### CODE REVIEW

**Comment by gregpriday** [comment]
It looks like this works the first time, but if you try insert a layout for the second time on a given page, it doesn't work.

Also, ideally we'd have a sort of confirmation when the user clicks on the main button.

Reckon this is a big interface improvement though.

**Comment by braamgenis** [comment]
@gregpriday Cool, I fixed the issue of inserting only working once. For the main button, I wonder if it should trigger an action at all? Just a thought, but shouldn't it rather just do nothing and require the user to select one of the dropdown (or is it dropup? :stuck_out_tongue: ) options?

**Comment by gregpriday** [comment]
But buttons love to be pushed! Looking at how Bootstrap treats these it seems like they use the click action to show the dropdown/riseup. Just hovering does nothing. So maybe this is the behaviour we want to use then.

**Comment by braamgenis** [comment]
Ok, it's working on click now. Hopefully that does the trick.

**Comment by gregpriday** [comment]
Yeah, think this is the one.

**Pull request merged**
